#ifndef INCLUDE_MEMORYMAP_H_
#define INCLUDE_MEMORYMAP_H_

/*
 * STM32F103RB RAM Layout
 * RAM: 0x20000000 - 0x20004FFF (Total: 20KB)
 */

#define RAM_START	0x20000000
#define RAM_SIZE	(20 * 1024)
#define RAM_END		(RAM_START + RAM_SIZE)

#define SYS_STACK_SIZE		1024	// Main stack: 1KB

#define SYS_STACK_TOP    	RAM_END
#define SYS_STACK_BASE   	(SYS_STACK_TOP - SYS_STACK_SIZE) // 0x20004C00

#define TASK_STACK_TOP		SYS_STACK_BASE
#define TASK_STACK_AREA_SIZE 10240
#define TASK_STACK_SIZE		1024
#define MAX_TASK_NUM		(TASK_STACK_AREA_SIZE / TASK_STACK_SIZE)


#endif // INCLUDE_MEMORYMAP_H_

